sudo: required

services:
  - docker

before_install:
  - docker-compose -v
  - docker-compose build tests
  - docker-compose run --rm tests composer install
  - docker-compose run --rm -e CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN tests

script:
  - docker pull quay.io/keboola/developer-portal-cli-v2:latest
  - export REPOSITORY=`docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD quay.io/keboola/developer-portal-cli-v2:latest ecr:get-repository keboola keboola.wr-redshift-v2`
  - docker tag $KBC_APP_REPOSITORY:latest $REPOSITORY:master
  - eval $(docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD quay.io/keboola/developer-portal-cli-v2:latest ecr:get-login keboola keboola.wr-redshift-v2)
  - docker push $REPOSITORY:master
  # Run live test job on new master image
  - docker pull quay.io/keboola/syrup-cli:latest
  - docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job keboola.wr-redshift-v2 289011092 master
  - docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job keboola.wr-redshift-v2 289011175 master

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true

notifications:
  slack: $SLACK_INTEGRATION_DOMAIN:$SLACK_INTEGRATION_KEY
