sudo: required

services:
  - docker

script:
  - docker-composer build
  - docker-compose run --rm app composer ci

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true

notifications:
  slack: $SLACK_INTEGRATION_DOMAIN:$SLACK_INTEGRATION_KEY
